on:
  pull_request:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-20.04
    container: ghcr.io/paulhatch/plgo:1.4.3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
      - name: Build Extension
        run: |
          echo $VERSION
          echo $version
          echo steps.version.outputs.version
